name: 'tech_job_market'
version: '1.0.0'
config-version: 2
profile: 'tech_job_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  tech_job_market:
    staging:
      +materialized: view
    core:
      +materialized: table
